import { useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { Button, FormControl, FormLabel, Input } from '@chakra-ui/react';
import { Container, LoginContainer, ContainerRegister, ImageContainer, ButtonContainer } from '../../styles/pages/login/style';

export default function LoginPage() {
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setLoading(true);
        try {
            const response = await fetch('https://marcacao-sala.vercel.app/auth/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ email, password }),
            });

            if (response.ok) {
                const data = await response.json();
                const token = data.token; // Assume que a resposta contém o token

                // Armazenar o token no localStorage
                localStorage.setItem('token', token);

                // Redirecionar para a página de professores
                router.push('/');
            } else {
                setError('Erro ao fazer login. Verifique suas credenciais.');
            }
        } catch (error) {
            setError('Erro ao fazer login. Por favor, tente novamente mais tarde.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            <Head>
                <title>Laboratório B208</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <LoginContainer>
                    <h1>Bem-vindo ao agendamento do laboratório B 208</h1>
                    <form onSubmit={handleSubmit}>
                        <FormControl>
                            <Input type='email' placeholder='Email' value={email} onChange={(e) => setEmail(e.target.value)} marginBottom='20px'/>

                            <Input type='password' placeholder='Senha' value={password} onChange={(e) => setPassword(e.target.value)} />

                            {error && <p>{error}</p>}

                            <ButtonContainer>
                                <Button
                                    mt={4}
                                     bg="#006a12" 
                                    _hover={{ bg: 'green.500' }} 
                                    color="white" 
                                    type='submit'
                                    isLoading={loading}
                                >
                                    Entrar
                                </Button>
                            </ButtonContainer>
                        </FormControl>
                    </form>
                </LoginContainer>
                <ContainerRegister>
                    {/* Seu conteúdo aqui */}
                </ContainerRegister>
            </Container>
        </>
    );
}
